# Generated by Django 2.1 on 2021-11-30 07:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20211130_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 7, 5, 29, 441635, tzinfo=utc)),
        ),
    ]
