# Generated by Django 2.1 on 2021-11-30 08:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20211130_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 8, 49, 49, 434790, tzinfo=utc)),
        ),
    ]
