# Generated by Django 3.2 on 2021-11-30 08:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20211130_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 8, 53, 48, 319649, tzinfo=utc)),
        ),
    ]
