# Generated by Django 2.1.5 on 2021-12-07 07:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20211130_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 7, 58, 1, 97819, tzinfo=utc)),
        ),
    ]
